app = "jeffersonlegacy"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile.galene"

[[services]]
  protocol = "tcp"
  internal_port = 8088
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

[[services]]
  protocol = "udp"
  internal_port = 1194
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[services.ports]]
    port = 1194

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
  cpus = 1
